language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

#set environmet variables
env:
  - PYTHONPATH=$TRAVIS_BUILD_DIR/themonitor

# command to run tests
script:
  - pwd
  - cd Themonitor/test
  - ls
  - python themonitor_test.py
